spring:
  application:
    name: jam-scada
  datasource:
    initialize: false
  thymeleaf:
    cache: false
    prefix: classpath:/com/codependent/rx/samplescada/templates/

server:
  port: 10000
  
logging:
#   file: /var/memento/security.log
  level:
    com.codependent: 'DEBUG'