spring:
  application:
    name: videoapi-microservice
  datasource:
    initialize: false
    
server:
  port: 9997

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
hystrix:
  command:
    getVideoBasicInfo:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  
    getVideoRating:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  

logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'