spring:
  application:
    name: videoinfo-microservice
  jpa:
    hibernate:
      ddl-auto: update
    
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
videoService:
  getVideoBasicInfo:
    delay: 200
  getVideoRating:
    delay: 200
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'
