spring:
  application:
    name: videoapi-microservice
    
server:
  port: 9997

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  
logging:
#   file: /var/memento/security.log
  level:
    org.springframework.web: 'DEBUG'