spring:
  name: videoApplication
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:9999}
  
threadExecutor:
  corePoolSize: 20
  maxPoolSize: 40
  
videoServiceImpl.service:
  delay: 200
  
videoService:
  getVideoBasicInfo:
    delay: 200
  getVideoRating:
    delay: 200